### ISSUE TITLE
did it occur the send half message or  messages concat when recieve or send?

### ISSUE THREAD

**Issue by irunmyway** [WeibelLab/Comms-Unity#4]

**Comment by tlsharkey** [comment]
With Reliable Communication, we use a TCP protocol which sends a 'stream' of information rather than individual messages. In this sense, messages are already broken up into pieces and then reassembled. 
Alternatively, you could send separate binary messages that each has a header describing its type. You would then have to reassemble the messages yourself based on your custom headers. But I imagine it would be easier to simple wait until the entire message is assembled before sending to avoid adding complexity. Perhaps I am simply missing something. Can you give an example / use case for why you might want this functionality?
